export const terrainType = {
  OCEAN: 'OCEAN',
  SEA: 'SEA',
  SHALLOW_WATER: 'SHALLOW_WATER', // <<< НОВЫЙ ТИП
  RIVER: 'RIVER',
  WET_SAND: 'WET_SAND',
  SAND: 'SAND',
  DRY_SAND: 'DRY_SAND',
  DRY_GRASS: 'DRY_GRASS',
  GRASS: 'GRASS',
  WET_GRASS: 'WET_GRASS',
  MOUNTAIN_SNOW: 'MOUNTAIN_SNOW',
  MOUNTAIN_ORE: 'MOUNTAIN_ORE',
  MOUNTAIN: 'MOUNTAIN',
  FOREST: 'FOREST',
  GRASS_HIGHLAND: 'GRASS_HIGHLAND',
  FOREST_HIGHLAND: 'FOREST_HIGHLAND',
  STONE_CLIFF: 'STONE_CLIFF'
};